### ISSUE TITLE
Request to be a contributor

### ISSUE THREAD

**Issue by dionjwa** [HaxeFoundation/hxnodelibs#15]
Hi. I'd like to become a contributor so I can help with PR reviews, since I will be regularly submitting PRs myself.

**Comment by nadako** [comment]
Good idea!

**Comment by dionjwa** [comment]
So I'm not able to review or accept other people's PRs.

**Comment by nadako** [comment]
Hmm, weird, i added you to the hxnodejs team, let's see...

**Comment by dionjwa** [comment]
Works now! Cheers!
