### ISSUE TITLE
WebSocketServer usage

### ISSUE THREAD

**Issue by Simn** [HaxeFoundation/hxnodelibs#4]
Someone on #haxe asked how to use this class: https://github.com/HaxeFoundation/hxnodelibs/blob/master/js/node/ws/WebSocketServer.hx

The problem is that the WebSocketServerOption class has no constructor, so there's nothing you can pass to the constructor of WebSocketServer. That type should either be a typedef structure or get a constructor, depending on what makes more sense.

@eduardo-costa

**Comment by andyli** [comment]
It should be an anon type... Fixed in #6.
